close all; clear all; clc;
fileNames = {'synthetic_control', 'Gun_Point', 'CBF', 'FaceAll', 'OSULeaf',...
    'SwedishLeaf', '50words', 'Trace', 'Two_Patterns', 'wafer', 'FaceFour', ...
    'Lighting2', 'Lighting7', 'ECG200', 'Adiac', 'yoga', 'FISH', 'Plane', ...
    'Car', 'Beef', 'Coffee', 'OliveOil', 'CinC_ECG_torso', ...
    'ChlorineConcentration', 'DiatomSizeReduction', 'ECGFiveDays', 'FacesUCR', ...
    'Haptics', 'InlineSkate', 'ItalyPowerDemand', 'MALLAT', 'MedicalImages', ...
    'MoteStrain', 'SonyAIBORobotSurfaceII', 'SonyAIBORobotSurface', ...
    'StarLightCurves', 'Symbols', 'TwoLeadECG', 'WordsSynonyms', 'Cricket_X', ...
    'Cricket_Y', 'Cricket_Z', 'uWaveGestureLibrary_X', 'uWaveGestureLibrary_Y',...
    'uWaveGestureLibrary_Z', 'NonInvasiveFatalECG_Thorax1', 'NonInvasiveFatalECG_Thorax2'};

dataDir = '../data/';
mean_stddev_all = zeros(length(fileNames),4);
for ind = 1:length(fileNames)
    origTrnTS = sortrows(load(strcat(dataDir, char(fileNames(ind)), '_TRAIN')));
    origTstTS = sortrows(load(strcat(dataDir, char(fileNames(ind)), '_TEST')));
    origTrnTS_sum = sum(origTrnTS(:, 2:end), 2);
    origTstTS_sum = sum(origTstTS(:, 2:end), 2);
%     disp(char(fileNames(ind)))
    mean_stddev_all(ind,:) = [mean(origTrnTS_sum); std(origTrnTS_sum); mean(origTstTS_sum); std(origTstTS_sum)];
end
disp(mean_stddev_all)
